# Generated by Django 5.0.6 on 2024-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
