# Generated by Django 5.0.6 on 2024-06-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodgroup',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='bloodgroup',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
