# Generated by Django 5.0.6 on 2024-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodgroup',
            old_name='quantity',
            new_name='quantity_available',
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='blood_group_name',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
    ]
