# Generated by Django 5.0.6 on 2024-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_rename_quantity_bloodgroup_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
